import { buildComfyPrompt, type PromptInput } from "./prompt";
import { lightingById, styleById } from "./presets";

/** ComfyUI UI-format graph. Drag onto the canvas to load. */
export function buildComfyWorkflow(input: PromptInput) {
  const { positive, negative } = buildComfyPrompt(input);
  const light = lightingById(input.lighting);
  const style = styleById(input.style);
  const denoise = Number((1.05 - input.lock * 0.55).toFixed(2));
  const cnStrength = Number((0.45 + input.lock * 0.4).toFixed(2));

  return {
    id: "lumen-hotel-relight",
    revision: 1,
    last_node_id: 16,
    last_link_id: 18,
    version: 0.4,
    extra: {
      workflow_title: "间光 · 酒店民宿结构锁定精修",
      lumen: {
        lighting: light.id,
        style: style.id,
        lock: input.lock,
        denoise,
        controlnet: cnStrength,
      },
    },
    groups: [
      {
        title: "1  载入",
        bounding: [40, 40, 380, 420],
        color: "#3f3f3f",
        font_size: 16,
      },
      {
        title: "2  结构锁  Depth + Canny",
        bounding: [460, 40, 520, 420],
        color: "#3f3f3f",
        font_size: 16,
      },
      {
        title: "3  Qwen Image Edit 2509 + Relight",
        bounding: [1020, 40, 640, 620],
        color: "#3f3f3f",
        font_size: 16,
      },
      {
        title: "4  出图对照",
        bounding: [1700, 40, 420, 520],
        color: "#3f3f3f",
        font_size: 16,
      },
    ],
    config: {},
    nodes: [
      note(
        1,
        [60, 80],
        [
          "间光 Lumen · 单工作流",
          "",
          `光线：${light.nameZh}  ${light.kelvin}`,
          `风格：${style.nameZh}`,
          `结构锁：${Math.round(input.lock * 100)}%`,
          `建议 denoise：${denoise}   ControlNet：${cnStrength}`,
          "",
          "模型放到 ComfyUI/models：",
          "· unet/qwen_image_edit_2509_fp8_e4m3fn.safetensors",
          "· clip/qwen_2.5_vl_7b_fp8.safetensors",
          "· vae/qwen_image_vae.safetensors",
          "· loras/Qwen-Image-Edit-2509-Lightning-8steps.safetensors",
          "· loras/Qwen-Edit-2509-Relight.safetensors",
          "· controlnet/InstantX-Qwen-Image-ControlNet-Union.safetensors",
          "",
          "缺节点：ComfyUI Manager → Install Missing Custom Nodes",
        ].join("\n"),
      ),
      {
        id: 2,
        type: "LoadImage",
        pos: [60, 360],
        size: [320, 60],
        flags: {},
        order: 0,
        mode: 0,
        inputs: [],
        outputs: [
          { name: "IMAGE", type: "IMAGE", links: [1, 2, 3, 17] },
          { name: "MASK", type: "MASK", links: null },
        ],
        properties: { "Node name for S&R": "LoadImage" },
        widgets_values: ["hotel-room.png", "image"],
      },
      {
        id: 3,
        type: "CannyEdgePreprocessor",
        pos: [480, 80],
        size: [240, 90],
        flags: {},
        order: 1,
        mode: 0,
        inputs: [{ name: "image", type: "IMAGE", link: 1 }],
        outputs: [{ name: "IMAGE", type: "IMAGE", links: [4] }],
        properties: {},
        widgets_values: [80, 180],
      },
      {
        id: 4,
        type: "DepthAnythingV2Preprocessor",
        pos: [480, 220],
        size: [280, 80],
        flags: {},
        order: 2,
        mode: 0,
        inputs: [{ name: "image", type: "IMAGE", link: 2 }],
        outputs: [{ name: "IMAGE", type: "IMAGE", links: [5] }],
        properties: {},
        widgets_values: ["depth_anything_v2_vitl.pth"],
      },
      {
        id: 5,
        type: "UNETLoader",
        pos: [1040, 80],
        size: [380, 70],
        flags: {},
        order: 3,
        mode: 0,
        inputs: [],
        outputs: [{ name: "MODEL", type: "MODEL", links: [6] }],
        properties: {},
        widgets_values: ["qwen_image_edit_2509_fp8_e4m3fn.safetensors", "default"],
      },
      {
        id: 6,
        type: "LoraLoaderModelOnly",
        pos: [1040, 180],
        size: [380, 80],
        flags: {},
        order: 4,
        mode: 0,
        inputs: [{ name: "model", type: "MODEL", link: 6 }],
        outputs: [{ name: "MODEL", type: "MODEL", links: [7] }],
        properties: {},
        widgets_values: [
          "Qwen-Image-Edit-2509-Lightning-8steps-V1.0-bf16.safetensors",
          1.0,
        ],
      },
      {
        id: 7,
        type: "LoraLoaderModelOnly",
        pos: [1040, 290],
        size: [380, 80],
        flags: {},
        order: 5,
        mode: 0,
        inputs: [{ name: "model", type: "MODEL", link: 7 }],
        outputs: [{ name: "MODEL", type: "MODEL", links: [8] }],
        properties: {},
        widgets_values: ["Qwen-Edit-2509-Relight.safetensors", 0.85],
      },
      {
        id: 8,
        type: "CLIPLoader",
        pos: [1040, 400],
        size: [380, 80],
        flags: {},
        order: 6,
        mode: 0,
        inputs: [],
        outputs: [{ name: "CLIP", type: "CLIP", links: [9] }],
        properties: {},
        widgets_values: ["qwen_2.5_vl_7b_fp8_e4m3fn.safetensors", "qwen_image"],
      },
      {
        id: 9,
        type: "VAELoader",
        pos: [1040, 510],
        size: [380, 60],
        flags: {},
        order: 7,
        mode: 0,
        inputs: [],
        outputs: [{ name: "VAE", type: "VAE", links: [10, 11] }],
        properties: {},
        widgets_values: ["qwen_image_vae.safetensors"],
      },
      {
        id: 10,
        type: "TextEncodeQwenImageEditPlus",
        pos: [480, 360],
        size: [480, 200],
        flags: {},
        order: 8,
        mode: 0,
        inputs: [
          { name: "clip", type: "CLIP", link: 9 },
          { name: "vae", type: "VAE", link: 10 },
          { name: "image1", type: "IMAGE", link: 3 },
        ],
        outputs: [{ name: "CONDITIONING", type: "CONDITIONING", links: [12] }],
        properties: {},
        widgets_values: [positive],
      },
      {
        id: 11,
        type: "CLIPTextEncode",
        pos: [480, 590],
        size: [480, 80],
        flags: {},
        order: 9,
        mode: 0,
        inputs: [{ name: "clip", type: "CLIP", link: 9 }],
        outputs: [{ name: "CONDITIONING", type: "CONDITIONING", links: [13] }],
        properties: {},
        widgets_values: [negative],
      },
      {
        id: 12,
        type: "ControlNetLoader",
        pos: [780, 80],
        size: [220, 60],
        flags: {},
        order: 10,
        mode: 0,
        inputs: [],
        outputs: [{ name: "CONTROL_NET", type: "CONTROL_NET", links: [14] }],
        properties: {},
        widgets_values: ["InstantX-Qwen-Image-ControlNet-Union.safetensors"],
      },
      {
        id: 13,
        type: "ControlNetApplyAdvanced",
        pos: [780, 170],
        size: [220, 140],
        flags: {},
        order: 11,
        mode: 0,
        inputs: [
          { name: "positive", type: "CONDITIONING", link: 12 },
          { name: "negative", type: "CONDITIONING", link: 13 },
          { name: "control_net", type: "CONTROL_NET", link: 14 },
          { name: "image", type: "IMAGE", link: 4 },
        ],
        outputs: [
          { name: "positive", type: "CONDITIONING", links: [15] },
          { name: "negative", type: "CONDITIONING", links: [16] },
        ],
        properties: {},
        widgets_values: [cnStrength, 0.0, 0.85],
      },
      {
        id: 14,
        type: "KSampler",
        pos: [1460, 80],
        size: [280, 280],
        flags: {},
        order: 12,
        mode: 0,
        inputs: [
          { name: "model", type: "MODEL", link: 8 },
          { name: "positive", type: "CONDITIONING", link: 15 },
          { name: "negative", type: "CONDITIONING", link: 16 },
          { name: "latent_image", type: "LATENT", link: 18 },
        ],
        outputs: [{ name: "LATENT", type: "LATENT", links: [19] }],
        properties: {},
        widgets_values: [42, "fixed", 8, 1.0, "euler", "simple", denoise],
      },
      {
        id: 15,
        type: "VAEEncode",
        pos: [1460, 400],
        size: [220, 50],
        flags: {},
        order: 13,
        mode: 0,
        inputs: [
          { name: "pixels", type: "IMAGE", link: 3 },
          { name: "vae", type: "VAE", link: 11 },
        ],
        outputs: [{ name: "LATENT", type: "LATENT", links: [18] }],
        properties: {},
        widgets_values: [],
      },
      {
        id: 16,
        type: "VAEDecode",
        pos: [1760, 80],
        size: [220, 50],
        flags: {},
        order: 14,
        mode: 0,
        inputs: [
          { name: "samples", type: "LATENT", link: 19 },
          { name: "vae", type: "VAE", link: 11 },
        ],
        outputs: [{ name: "IMAGE", type: "IMAGE", links: [20] }],
        properties: {},
        widgets_values: [],
      },
      {
        id: 17,
        type: "SaveImage",
        pos: [1760, 170],
        size: [320, 60],
        flags: {},
        order: 15,
        mode: 0,
        inputs: [{ name: "images", type: "IMAGE", link: 20 }],
        outputs: [],
        properties: {},
        widgets_values: ["lumen/hotel"],
      },
      {
        id: 18,
        type: "ImageComparer+",
        pos: [1760, 280],
        size: [320, 240],
        flags: {},
        order: 16,
        mode: 0,
        inputs: [
          { name: "image_a", type: "IMAGE", link: 17 },
          { name: "image_b", type: "IMAGE", link: 20 },
        ],
        outputs: [],
        properties: {},
        widgets_values: [],
      },
    ],
    links: [
      [1, 2, 0, 3, 0, "IMAGE"],
      [2, 2, 0, 4, 0, "IMAGE"],
      [3, 2, 0, 10, 2, "IMAGE"],
      [4, 3, 0, 13, 3, "IMAGE"],
      [5, 4, 0, 13, 3, "IMAGE"],
      [6, 5, 0, 6, 0, "MODEL"],
      [7, 6, 0, 7, 0, "MODEL"],
      [8, 7, 0, 14, 0, "MODEL"],
      [9, 8, 0, 10, 0, "CLIP"],
      [10, 9, 0, 10, 1, "VAE"],
      [11, 9, 0, 16, 1, "VAE"],
      [12, 10, 0, 13, 0, "CONDITIONING"],
      [13, 11, 0, 13, 1, "CONDITIONING"],
      [14, 12, 0, 13, 2, "CONTROL_NET"],
      [15, 13, 0, 14, 1, "CONDITIONING"],
      [16, 13, 1, 14, 2, "CONDITIONING"],
      [17, 2, 0, 18, 0, "IMAGE"],
      [18, 15, 0, 14, 3, "LATENT"],
      [19, 14, 0, 16, 0, "LATENT"],
      [20, 16, 0, 17, 0, "IMAGE"],
    ],
  };
}

function note(id: number, pos: [number, number], text: string) {
  return {
    id,
    type: "MarkdownNote",
    pos,
    size: [340, 260],
    flags: {},
    order: 0,
    mode: 0,
    inputs: [],
    outputs: [],
    properties: {},
    widgets_values: [text],
  };
}

export const MODEL_PACK = [
  {
    name: "Qwen Image Edit 2509 FP8",
    path: "models/unet/qwen_image_edit_2509_fp8_e4m3fn.safetensors",
    href: "https://huggingface.co/Comfy-Org/Qwen-Image-Edit_ComfyUI",
  },
  {
    name: "Qwen 2.5 VL 7B CLIP",
    path: "models/clip/qwen_2.5_vl_7b_fp8_e4m3fn.safetensors",
    href: "https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI",
  },
  {
    name: "Qwen Image VAE",
    path: "models/vae/qwen_image_vae.safetensors",
    href: "https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI",
  },
  {
    name: "Lightning 8-step LoRA",
    path: "models/loras/Qwen-Image-Edit-2509-Lightning-8steps-V1.0-bf16.safetensors",
    href: "https://huggingface.co/lightx2v/Qwen-Image-Lightning",
  },
  {
    name: "Relight LoRA (dx8152)",
    path: "models/loras/Qwen-Edit-2509-Relight.safetensors",
    href: "https://huggingface.co/dx8152/Qwen-Image-Edit-2509-Relight",
  },
  {
    name: "InstantX ControlNet Union",
    path: "models/controlnet/InstantX-Qwen-Image-ControlNet-Union.safetensors",
    href: "https://huggingface.co/InstantX/Qwen-Image-ControlNet-Union",
  },
];

export const PIPELINE_STEPS = [
  {
    n: "01",
    title: "载入原图",
    body: "任意酒店 / 民宿实拍。建议长边 2K–4K，JPEG 即可。不要先用美图软件拉爆高光。",
  },
  {
    n: "02",
    title: "结构锁",
    body: "Canny 锁边缘（墙线、家具轮廓），DepthAnything V2 锁空间。两者叠在 ControlNet Union 上，strength 0.65–0.85。这是「东西不能动」的核心。",
  },
  {
    n: "03",
    title: "指令编码",
    body: "Qwen Image Edit 2509 吃自然语言。中文指令比英文更稳。第一句永远写「保持结构完全不变」。",
  },
  {
    n: "04",
    title: "Relight LoRA",
    body: "dx8152 的 Relight / Light Migration LoRA 专门改光照，不改几何。Lightning 8-step 把采样压到 8 步。",
  },
  {
    n: "05",
    title: "低 denoise 采样",
    body: "结构锁 80% 时 denoise 约 0.28。高于 0.45 家具开始漂移。CFG 保持 1.0（Qwen Edit 不需要高 CFG）。",
  },
  {
    n: "06",
    title: "对照 + 超分",
    body: "Image Comparer 左右拖看结构有没有跑。过关后再接 SeedVR2 或 Ultimate SD Upscale 出 4K 宣传图。",
  },
];
